version: "3"

services:

  # Web Application
  twiter:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - local.env
    ports:
      - "8000:8000"
    depends_on:
      - twiter_db
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"

  # Database
  twiter_db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"