# Generated by Django 4.2.7 on 2024-01-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='avatar',
            new_name='picture',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('AD', 'Andorra'), ('TO', 'Tonga'), ('BA', 'Bosnia And Herzegowina'), ('HR', 'Croatia'), ('IN', 'India'), ('KH', 'Cambodia'), ('UY', 'Uruguay'), ('SM', 'San Marino'), ('ZM', 'Zambia'), ('IQ', 'Iraq'), ('SV', 'El Salvador'), ('LC', 'Saint Lucia'), ('AI', 'Anguilla'), ('GL', 'Greenland'), ('NR', 'Nauru'), ('TJ', 'Tajikistan'), ('SO', 'Somalia'), ('UG', 'Uganda'), ('KW', 'Kuwait'), ('AE', 'United Arab Emirates'), ('SK', 'Slovakia'), ('SD', 'Sudan'), ('CH', 'Switzerland'), ('AQ', 'Antarctica'), ('RW', 'Rwanda'), ('YE', 'Yemen'), ('GW', 'Guinea-bissau'), ('TM', 'Turkmenistan'), ('CL', 'Chile'), ('MC', 'Monaco'), ('AF', 'Afghanistan'), ('NF', 'Norfolk Island'), ('TF', 'French S. Territories'), ('BG', 'Bulgaria'), ('LB', 'Lebanon'), ('PK', 'Pakistan'), ('DO', 'Dominican Republic'), ('PT', 'Portugal'), ('TZ', 'Tanzania'), ('BO', 'Bolivia'), ('MV', 'Maldives'), ('ER', 'Eritrea'), ('RE', 'Reunion'), ('AN', 'Netherlands Antilles'), ('LS', 'Lesotho'), ('IT', 'Italy'), ('JP', 'Japan'), ('VN', 'Viet Nam'), ('ET', 'Ethiopia'), ('NI', 'Nicaragua'), ('GQ', 'Equatorial Guinea'), ('FJ', 'Fiji'), ('TD', 'Chad'), ('NO', 'Norway'), ('MU', 'Mauritius'), ('CR', 'Costa Rica'), ('ZA', 'South Africa'), ('AT', 'Austria'), ('RO', 'Romania'), ('OM', 'Oman'), ('FR', 'France'), ('UA', 'Ukraine'), ('SC', 'Seychelles'), ('US', 'United States'), ('TV', 'Tuvalu'), ('PY', 'Paraguay'), ('ID', 'Indonesia'), ('SL', 'Sierra Leone'), ('GT', 'Guatemala'), ('MR', 'Mauritania'), ('EE', 'Estonia'), ('DE', 'Germany'), ('PR', 'Puerto Rico'), ('KG', 'Kyrgyzstan'), ('YT', 'Mayotte'), ('TW', 'Taiwan'), ('TN', 'Tunisia'), ('KR', 'Korea (South)'), ('SI', 'Slovenia'), ('BB', 'Barbados'), ('ML', 'Mali'), ('AZ', 'Azerbaijan'), ('MY', 'Malaysia'), ('VG', 'Virgin Islands (British)'), ('CN', 'China'), ('EH', 'Western Sahara'), ('FO', 'Faroe Islands'), ('HT', 'Haiti'), ('PG', 'Papua New Guinea'), ('HU', 'Hungary'), ('CU', 'Cuba'), ('CX', 'Christmas Island'), ('GI', 'Gibraltar'), ('AO', 'Angola'), ('LU', 'Luxembourg'), ('MN', 'Mongolia'), ('SH', 'St. Helena'), ('LT', 'Lithuania'), ('MZ', 'Mozambique'), ('DJ', 'Djibouti'), ('SE', 'Sweden'), ('FK', 'Falkland Islands (Malvinas)'), ('RU', 'Russian Federation'), ('KE', 'Kenya'), ('GF', 'French Guiana'), ('KP', 'Korea (North)'), ('LR', 'Liberia'), ('MX', 'Mexico'), ('TP', 'East Timor'), ('LV', 'Latvia'), ('MW', 'Malawi'), ('DZ', 'Algeria'), ('LY', 'Libya'), ('WS', 'Samoa'), ('BZ', 'Belize'), ('SG', 'Singapore'), ('KY', 'Cayman Islands'), ('IL', 'Israel'), ('CA', 'Canada'), ('PH', 'Philippines'), ('TR', 'Turkey'), ('GD', 'Grenada'), ('MS', 'Montserrat'), ('GA', 'Gabon'), ('SZ', 'Swaziland'), ('MG', 'Madagascar'), ('MK', 'Macedonia'), ('YU', 'Yugoslavia'), ('EC', 'Ecuador'), ('TT', 'Trinidad And Tobago'), ('CY', 'Cyprus'), ('GE', 'Georgia'), ('SY', 'Syrian Arab Republic'), ('AG', 'Antigua And Barbuda'), ('NL', 'Netherlands'), ('NU', 'Niue'), ('GM', 'Gambia'), ('ZR', 'Zaire'), ('BR', 'Brazil'), ('CF', 'Central African Rep'), ('JO', 'Jordan'), ('LA', 'Laos'), ('CG', 'Congo'), ('DM', 'Dominica'), ('LK', 'Sri Lanka'), ('DK', 'Denmark'), ('BT', 'Bhutan'), ('PA', 'Panama'), ('SR', 'Suriname'), ('AU', 'Australia'), ('BD', 'Bangladesh'), ('PF', 'French Polynesia'), ('NC', 'New Caledonia'), ('BW', 'Botswana'), ('GN', 'Guinea'), ('KM', 'Comoros'), ('MT', 'Malta'), ('CK', 'Cook Islands'), ('ST', 'Sao Tome'), ('VC', 'St Vincent/Grenadines'), ('BE', 'Belgium'), ('PW', 'Palau'), ('BV', 'Bouvet Island'), ('TG', 'Togo'), ('BN', 'Brunei Darussalam'), ('AW', 'Aruba'), ('ES', 'Spain'), ('IR', 'Iran'), ('LI', 'Liechtenstein'), ('NP', 'Nepal'), ('PM', 'St.Pierre'), ('GR', 'Greece'), ('GH', 'Ghana'), ('MM', 'Myanmar'), ('BF', 'Burkina Faso'), ('NZ', 'New Zealand'), ('HN', 'Honduras'), ('FI', 'Finland'), ('JM', 'Jamaica'), ('NG', 'Nigeria'), ('VU', 'Vanuatu'), ('BY', 'Belarus'), ('CI', 'Cote D`ivoire'), ('UZ', 'Uzbekistan'), ('AM', 'Armenia'), ('EG', 'Egypt'), ('PN', 'Pitcairn'), ('CZ', 'Czech Republic'), ('PL', 'Poland'), ('CM', 'Cameroon'), ('BM', 'Bermuda'), ('BS', 'Bahamas'), ('MQ', 'Martinique'), ('CC', 'Cocos Islands'), ('CV', 'Cape Verde'), ('CO', 'Colombia'), ('MO', 'Macau'), ('NE', 'Niger'), ('SA', 'Saudi Arabia'), ('BJ', 'Benin'), ('UK', 'United Kingdom'), ('PE', 'Peru'), ('VA', 'Vatican City State'), ('NA', 'Namibia'), ('IE', 'Ireland'), ('VE', 'Venezuela'), ('GP', 'Guadeloupe'), ('MD', 'Moldova'), ('MP', 'Northern Mariana Islands'), ('VI', 'Virgin Islands (U.S.)'), ('GU', 'Guam'), ('SN', 'Senegal'), ('AL', 'Albania'), ('AR', 'Argentina'), ('BH', 'Bahrain'), ('KN', 'Saint Kitts And Nevis'), ('MA', 'Morocco'), ('QA', 'Qatar'), ('TK', 'Tokelau'), ('BI', 'Burundi'), ('TH', 'Thailand'), ('FM', 'Micronesia'), ('AS', 'American Samoa'), ('MH', 'Marshall Islands'), ('GY', 'Guyana'), ('ZW', 'Zimbabwe'), ('HK', 'Hong Kong'), ('IS', 'Iceland'), ('SB', 'Solomon Islands'), ('KI', 'Kiribati'), ('KZ', 'Kazakhstan')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birthday',
            field=models.DateTimeField(),
        ),
    ]
